### ISSUE TITLE
No active context found to set property request.user_key

### ISSUE THREAD

**Issue by bin4ryio** [NarHakobyan/awesome-nest-boilerplate#1]
Bump into this error when I try to access protected endpoint.

```
[Nest] 99681   - 2019-04-17 17:54   [ExceptionsHandler] No active context found to set property request.user_key +637ms
Error: No active context found to set property request.user_key
    at Object.setContext (/Users/darris/Playground/grammes-api/node_modules/request-context/lib/index.js:98:9)
    at Function.set (/Users/darris/Playground/grammes-api/src/providers/context.service.ts:11:24)
    at Function.setAuthUser (/Users/darris/Playground/grammes-api/src/modules/auth/auth.service.ts:54:24)
    at AuthUserInterceptor.intercept (/Users/darris/Playground/grammes-api/src/interceptors/auth-user-interceptor.service.ts:20:21)
    at /Users/darris/Playground/grammes-api/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:21:36
    at Object.handle (/Users/darris/Playground/grammes-api/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:19:56)
    at ClassSerializerInterceptor.intercept (/Users/darris/Playground/grammes-api/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:34:14)
    at /Users/darris/Playground/grammes-api/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:21:36
    at InterceptorsConsumer.intercept (/Users/darris/Playground/grammes-api/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:24)
    at /Users/darris/Playground/grammes-api/node_modules/@nestjs/core/router/router-execution-context.js:41:60
::1 - - [17/Apr/2019:09:54:53 +0000] "GET /auth/me HTTP/1.1" 500 52 "-" "insomnia/6.3.2"
```

**Comment by NarHakobyan** [comment]
@bin4ryio Hi, thanks for issue, could you please send example application for that issue?

**Comment by NarHakobyan** [comment]
closed for now.
