### ISSUE TITLE
error TS2550: Property 'replaceAll' does not exist on type 'string'.

### ISSUE THREAD

**Issue by little-buddy** [NarHakobyan/awesome-nest-boilerplate#325]
https://github.com/NarHakobyan/awesome-nest-boilerplate/blob/bddf194a358dd204298e44c7c99f82e489f1ae55/src/snake-naming.strategy.ts#L40
Template environment configuration issue

**Comment by mpenna** [comment]
In my case, once the "target" field in tsconfig.json is set to ES2021, another error is returned when running `yarn start:dev`:

```bash
src/common/utils.ts:44:3 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

44   return memberParts.at(-1);
     ~~~~~~

    at createTSError (/workspaces/nestjs-awesome-blrplate/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/workspaces/nestjs-awesome-blrplate/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/workspaces/nestjs-awesome-blrplate/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/workspaces/nestjs-awesome-blrplate/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/workspaces/nestjs-awesome-blrplate/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/workspaces/nestjs-awesome-blrplate/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  diagnosticCodes: [ 2322 ]
}
error Command failed with exit code 1.
```

**Comment by zhengbangbo** [comment]
I have the same issue @mpenna

**Comment by bachlongkocanh** [comment]
Same issue

**Comment by NarHakobyan** [comment]
Hey guys, All fixed, and target version updated.
