### ISSUE TITLE
Eslint Not working

### ISSUE THREAD

**Issue by hyprocritor** [NarHakobyan/awesome-nest-boilerplate#330]
Got the following error while running the eslint:
I runned the the command in both local and GitHub codespace and got the same error
```
@(username)➜ /workspaces/awesome-nest-boilerplate (main) $ yarn run lint:fix
yarn run v1.22.19
$ eslint --fix . --ext .ts

Oops! Something went wrong! :(

ESLint: 8.47.0

RangeError: Line number out of range (line 183 requested, but only 13 lines present).
Occurred while linting /workspaces/awesome-nest-boilerplate/src/decorators/index.ts:1
Rule: "canonical/no-unused-exports"
    at SourceCode.getIndexFromLoc (/workspaces/awesome-nest-boilerplate/node_modules/eslint/lib/source-code/source-code.js:582:19)
    at Program (/workspaces/awesome-nest-boilerplate/node_modules/eslint-plugin-canonical/dist/src/rules/noUnusedExports.js:31:46)
    at ruleErrorHandler (/workspaces/awesome-nest-boilerplate/node_modules/eslint/lib/linter/linter.js:1050:28)
    at /workspaces/awesome-nest-boilerplate/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/workspaces/awesome-nest-boilerplate/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/workspaces/awesome-nest-boilerplate/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/workspaces/awesome-nest-boilerplate/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/workspaces/awesome-nest-boilerplate/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/workspaces/awesome-nest-boilerplate/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

I also get multiple issue after turnning off the this rule.

**Comment by hxtruong6** [comment]
hi, any update for this issue?

**Comment by NarHakobyan** [comment]
it's already fixed, and migrated to version v9
