### ISSUE TITLE
Incompatibility to convert entity to dto class instance with typeorm@next

### ISSUE THREAD

**Issue by gl63** [NarHakobyan/awesome-nest-boilerplate#35]
After updating typeorm@next (0.3.0-alpha.24) the error below is displayed
```
TypeError: model is not a constructor
    at Function.toDto (utils.service.ts?:12:16)
    at ClientsEntity.toDto (abstract.entity.ts?:41:45)
    at eval (boilerplate.polyfill.ts?:7:29)
    at arrayMap (/lodash/lodash.js:639:23)
    at Function.map (/lodash/lodash.js:9554:14)
    at interceptor (/lodash/lodash.js:16997:35)
    at thru (/lodash/lodash.js:8795:14)
    at /lodash/lodash.js:4368:28
    at arrayReduce (/lodash/lodash.js:683:21)
    at baseWrapperValue (/lodash/lodash.js:4367:14)
```

**Comment by NarHakobyan** [comment]
Hi @gl63,

We are not using alpha versions because they are not stable. Will update typeorm when it will release the next stable version.
