### ISSUE TITLE
TypeError: Class constructor ProjectDto cannot be invoked without 'new'

### ISSUE THREAD

**Issue by geongeorge** [NarHakobyan/awesome-nest-boilerplate#44]
Thank you for this project!

I was trying to add a projects endpoint so I added a project entity and projectCreate entity.

The project creation worked flawlessly but When trying to fetch the project using a query param, I get this error:

```
SELECT "project"."id" AS "project_id", "project"."created_at" AS "project_created_at", "project"."updated_at" AS "project_updated_at", "project"."name" AS "project_name" FROM "projects" "project" WHERE "project"."id" = $1 -- PARAMETERS: ["1"]
[Nest] 34697   - 08/15/2020, 2:24:58 PM   [ExceptionsHandler] Class constructor ProjectDto cannot be invoked without 'new' +2370ms
TypeError: Class constructor ProjectDto cannot be invoked without 'new'
    at _loop_1 (/Users/geongeorge/Work/PhotoApi/backend/bigleap/src/TransformOperationExecutor.ts:154:47)
    at TransformOperationExecutor.transform (/Users/geongeorge/Work/PhotoApi/backend/bigleap/node_modules/class-transformer/TransformOperationExecutor.js:260:17)
    at ClassTransformer.classToPlain (/Users/geongeorge/Work/PhotoApi/backend/bigleap/src/ClassTransformer.ts:21:25)
    at Object.classToPlain (/Users/geongeorge/Work/PhotoApi/backend/bigleap/src/index.ts:17:29)
    at ClassSerializerInterceptor.transformToPlain (/Users/geongeorge/Work/PhotoApi/backend/bigleap/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:40:32)
    at ClassSerializerInterceptor.serialize (/Users/geongeorge/Work/PhotoApi/backend/bigleap/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:36:20)
    at MapSubscriber.project (/Users/geongeorge/Work/PhotoApi/backend/bigleap/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:27:49)
    at MapSubscriber._next (/Users/geongeorge/Work/PhotoApi/backend/bigleap/node_modules/rxjs/src/internal/operators/map.ts:84:29)
    at MapSubscriber.Subscriber.next (/Users/geongeorge/Work/PhotoApi/backend/bigleap/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MergeMapSubscriber.notifyNext (/Users/geongeorge/Work/PhotoApi/backend/bigleap/node_modules/rxjs/src/internal/operators/mergeMap.ts:166:22)
```

I haven't made many changes to the boilerplate.

### project.entity.ts

```ts
import { Column, Entity } from 'typeorm';

import { AbstractEntity } from '../../common/abstract.entity';
import { ProjectDto } from './dto/ProjectDto';

@Entity({ name: 'projects' })
export class ProjectEntity extends AbstractEntity<ProjectDto> {
    @Column({ nullable: true })
    name: string;

    dtoClass = ProjectDto;
}
```

### projectDto.ts

```ts
'use strict';
import { ApiProperty } from '@nestjs/swagger';

import { ProjectEntity } from '../project.entity';
import { AbstractDto } from './../../../common/dto/AbstractDto';

export class ProjectDto extends AbstractDto {
    @ApiProperty()
    name: string;

    constructor(project: ProjectEntity) {
        super(project);
        this.name = project.name;
    }
}

```

### project.service.ts

```ts
...
findOne(findData: any) {
        return this.projectRepository.findOne(findData);
    }
...

```

### project.repository.ts

```ts
import { Repository } from 'typeorm';
import { EntityRepository } from 'typeorm/decorator/EntityRepository';

import { ProjectEntity } from './project.entity';

@EntityRepository(ProjectEntity)
export class ProjectRepository extends Repository<ProjectEntity> {}

```

I'm not sure why the user to works and why not the project dto.

# The Fix

I'm not sure if this is the right way but I saw someone else facing this issue.
This did fix my issue but it adds the `@Exclude()` decorator to 'dtoClass` param in `AbstractEntity`

The fix is: https://github.com/nestjsx/crud/issues/411#issuecomment-599312180

**Comment by NarHakobyan** [comment]
Hi, is it still actual?

**Comment by geongeorge** [comment]
@NarHakobyan Yes, I had to do what is mentioned in that comment to get this working. Please let me know if there is an alternative

**Comment by NarHakobyan** [comment]
@geongeorge can you please show me example of your controller?

**Comment by geongeorge** [comment]
@NarHakobyan Invited you here: https://github.com/geongeorge/pixelplug-backend-nest/invitations

**Comment by NarHakobyan** [comment]
@geongeorge you need to call `toDto()` before returning the value in the controller

```typescript
const projectEntity = await this._projectService.createProject({
            ...projectCreateDto,
            user,
        });
return projectEntity.toDto();
```

Note: I will add autoconversion in boilerplate

**Comment by geongeorge** [comment]
@NarHakobyan Thank you for taking a look :) I guess that was the issue
